[package]
name = "singlefile"
version = "0.3.0"
authors = ["ScottyThePilot <scotty.codes@gmail.com>"]
edition = "2021"

[dependencies]
fs4 = "0.6"
serde = "1.0"

[dependencies.tokio]
version = "1"
features = ["rt", "sync"]
optional = true

[features]
default = []
tokio = ["dep:tokio"]
